jobs:
    beagle-trigger:
        docker:
            - image: beaglesecurity/beagle-test-trigger-common:latest
        steps:
            - run:
                command: trigger-test
workflows:
    version: 2
    workame:
        jobs:
            - beagle-trigger

